const ENGLISH_LETTERS_BY_ORDER = [
  "e",
  "t",
  "a",
  "o",
  "i",
  "n",
  "s",
  "h",
  "r",
  "d",
  "l",
  "c",
  "u",
  "m",
  "w",
  "f",
  "g",
  "y",
  "p",
  "b",
  "v",
  "k",
  "j",
  "x",
  "q",
  "z",
];

const ENGLISH_DOUBLE_LETTERS = [
  "l",
  "s",
  "e",
  "o",
  "t",
  "f",
  "p",
  "r",
  "m",
  "c",
  "n",
  "d",
  "g",
  "i",
  "b",
];

const ONE_LETTER_WORDS = ["a", "i"];

const ABBREVIATED_SHORT_VERB = {
  "you're": "you are",
  "he's": "he is",
  "she's": "she is",
  "we're": "we are",
  "it's": "it is",
  "isn't": "is not",
  "aren't": "are not",
  "they're": "they are",
  "there's": "there is",
  "wasn't": "was not",
  "weren't": " were not",
  "I've": "I have",
  "you've": " you have",
  "he's": "he has",
  "she's": "she has",
  "it's": "it has",
  "we've": "we have",
  "they've": "they have",
  "there's": " there has",
  "hasn't": "has not",
  "haven't": "have not",
  "I'd": "I had",
  "you'd": "you had",
  "he'd": "he had",
  "she'd": "she had",
  "it'd": "it had",
  "we'd": "we had",
  "they'd": "they had",
  "doesn't": "does not",
  "don't": "do not",
  "didn't": "did not",
  "I'll": "I will",
  "you'll": "you will",
  "he'll": "he will",
  "she'll": "she will",
  "we'll": "we will",
  "they'll": "they will",
  "there'll": "there will",
  "I'd": "I would",
  "you'd": "you would",
  "he'd": "he would",
  "she'd": "she would",
  "it'd": "it would",
  "we'd": "we would",
  "they'd": "they would",
  "there'd": "there had",
  "there'd": "there would",
  "can't": "cannot",
  "couldn't": "could not",
  "daren't": "dare not",
  "hadn't": "had not",
  "mightn't": "might not",
  "mustn't": "must not",
  "needn't": "need not",
  "oughtn't": "ought not",
  "shan't": "shall not",
  "shouldn't": "should not",
  "usedn't": "used not",
  "won't": "will not",
  "wouldn't": "would not",
};

module.exports = {
  ENGLISH_LETTERS_BY_ORDER,
  ENGLISH_DOUBLE_LETTERS,
  ONE_LETTER_WORDS,
  ABBREVIATED_SHORT_VERB,
};
